package co.edu.uniquindio.compiladores.lexico

enum class Categoria {

        ENTERO,
        REAL,
        CARACTER,
        IDENTIFICADOR,
        CADENA_CARACTERES,
        CADENA_CARACTERES_SIN_CERRAR,
        OPERADOR_ARITMETICO,
        PALABRA_RESERVADA,
        OPERADOR_RELACIONAL,
        OPERADOR_LOGICO,
        OPERADOR_BINARIO,
        OPERADOR_DE_ASIGNACION,
        OPERADOR_DE_INCREMENTO,
        OPERADOR_DE_DECREMENTO,
        PARENTESIS_APERTURA,
        PARENTESIS_CIERRE,
        LLAVE_APERTURA,
        LLAVE_CIERRE,
        CORCHETE_APERTURA,
        CORCHETE_CIERRE,
        TERMINAL_FIN_SENTENCIA,
        DOS_PUNTOS,
        SEPARADOR,
        COMENTARIO_DE_LINEA,
        COMENTARIO_DE_BLOQUE,
        COMENTARIO_DE_BLOQUE_SIN_CERRAR,
        DESCONOCIDO
}